modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="one_piece_elite"
version="1.0.0"
displayName="One Piece Elite"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="charl, MCreator"

[[dependencies.one_piece_elite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




